// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STManagemenet.Models;

namespace STManagemenet.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("STManagemenet.Models.Filiere", b =>
                {
                    b.Property<int>("Id_filiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_filiere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_filiere");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("STManagemenet.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_filiere")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_filiere");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("STManagemenet.Models.Student", b =>
                {
                    b.HasOne("STManagemenet.Models.Filiere", "Filiere")
                        .WithMany("Students")
                        .HasForeignKey("Id_filiere");
                });
#pragma warning restore 612, 618
        }
    }
}
